# Generated by Django 5.0.5 on 2024-05-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
